[[NLopt]]
arch = "aarch64"
git-tree-sha1 = "8eaf75cb78001abd7226a67a9fc26488bf94f4f3"
os = "macos"

    [[NLopt.download]]
    sha256 = "9d3bcd81ca220a8761a21074d8073012720394f20b26499da1b5718af59c6976"
    url = "https://github.com/JuliaBinaryWrappers/NLopt_jll.jl/releases/download/NLopt-v2.8.0+0/NLopt.v2.8.0.aarch64-apple-darwin.tar.gz"
[[NLopt]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "993d2868c87c674da0147699b60ede23db3de3cb"
libc = "glibc"
os = "linux"

    [[NLopt.download]]
    sha256 = "4761d38548054aa27b26dc155f71db8f1155630b12ce3d6ba9b1386f1525fc0d"
    url = "https://github.com/JuliaBinaryWrappers/NLopt_jll.jl/releases/download/NLopt-v2.8.0+0/NLopt.v2.8.0.aarch64-linux-gnu-cxx03.tar.gz"
[[NLopt]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "9ebba3eff28b6e19787e34e2f60de9c3ac40f12e"
libc = "glibc"
os = "linux"

    [[NLopt.download]]
    sha256 = "6d8e48f6267fd6c8675745e5749bad90f3d411c1f7eec17a1ea88a6b68000cee"
    url = "https://github.com/JuliaBinaryWrappers/NLopt_jll.jl/releases/download/NLopt-v2.8.0+0/NLopt.v2.8.0.aarch64-linux-gnu-cxx11.tar.gz"
[[NLopt]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "0e23cf42474c5f55f633de53bc0e0bc345293f6e"
libc = "musl"
os = "linux"

    [[NLopt.download]]
    sha256 = "a1ea4bf1f0aa387bdc6cea006b9c964296ee2052d5612ed6a3c18f84c30a5fe6"
    url = "https://github.com/JuliaBinaryWrappers/NLopt_jll.jl/releases/download/NLopt-v2.8.0+0/NLopt.v2.8.0.aarch64-linux-musl-cxx03.tar.gz"
[[NLopt]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3a1b8151746e06134c0eca88520e25d1c68335cb"
libc = "musl"
os = "linux"

    [[NLopt.download]]
    sha256 = "e35c1905cc4748952f813184967daefbab15817a657e5722380931908fdbf07b"
    url = "https://github.com/JuliaBinaryWrappers/NLopt_jll.jl/releases/download/NLopt-v2.8.0+0/NLopt.v2.8.0.aarch64-linux-musl-cxx11.tar.gz"
[[NLopt]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "37ff90cab276fe13619bf6d48d80c550ecf5590b"
libc = "glibc"
os = "linux"

    [[NLopt.download]]
    sha256 = "e1c39c8ce7d0716b8d06b15b5dea3f6900c9735ec56f4183bbe326b236520dcd"
    url = "https://github.com/JuliaBinaryWrappers/NLopt_jll.jl/releases/download/NLopt-v2.8.0+0/NLopt.v2.8.0.armv6l-linux-gnueabihf-cxx03.tar.gz"
[[NLopt]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "7a890ee1497055adffb24cdcb0d3e9815d779ab4"
libc = "glibc"
os = "linux"

    [[NLopt.download]]
    sha256 = "a146d53a7011ca1d07b4899040549d51f4724e02ddb4ee85adad7ad8547e9314"
    url = "https://github.com/JuliaBinaryWrappers/NLopt_jll.jl/releases/download/NLopt-v2.8.0+0/NLopt.v2.8.0.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[NLopt]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "8f90297652780ef3d1232528e559b57d42c37864"
libc = "musl"
os = "linux"

    [[NLopt.download]]
    sha256 = "5568996a53ae216188ba0725ae852b471cece8bc29887409b0b897e384bb3ecf"
    url = "https://github.com/JuliaBinaryWrappers/NLopt_jll.jl/releases/download/NLopt-v2.8.0+0/NLopt.v2.8.0.armv6l-linux-musleabihf-cxx03.tar.gz"
[[NLopt]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "291f615e159fb1f359f049d796934ee2fcd8816d"
libc = "musl"
os = "linux"

    [[NLopt.download]]
    sha256 = "0830a5235764fca521192fadda44a7509b7e1e9383cf90c581624cf623d4e0d8"
    url = "https://github.com/JuliaBinaryWrappers/NLopt_jll.jl/releases/download/NLopt-v2.8.0+0/NLopt.v2.8.0.armv6l-linux-musleabihf-cxx11.tar.gz"
[[NLopt]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "3c5642fa6ccd1a9b34a2b88e171bc22529e94621"
libc = "glibc"
os = "linux"

    [[NLopt.download]]
    sha256 = "ca2fb3079db8bc3249ab09622ef6fe9754ac96ebacb5263f541d4ea3be13b3a8"
    url = "https://github.com/JuliaBinaryWrappers/NLopt_jll.jl/releases/download/NLopt-v2.8.0+0/NLopt.v2.8.0.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[NLopt]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "73c3dd0d0c1945885bbf322c5a41001273a39a18"
libc = "glibc"
os = "linux"

    [[NLopt.download]]
    sha256 = "d31415febb4b8dff1627beac0014d692b18d319d2e864abde29941820d242db8"
    url = "https://github.com/JuliaBinaryWrappers/NLopt_jll.jl/releases/download/NLopt-v2.8.0+0/NLopt.v2.8.0.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[NLopt]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "bcf4d027da43b525d540ea74605e02f186aec7cc"
libc = "musl"
os = "linux"

    [[NLopt.download]]
    sha256 = "489afc48f2df0516b8dd68b43a4428cfeaf455273d60e591719a85ee220db540"
    url = "https://github.com/JuliaBinaryWrappers/NLopt_jll.jl/releases/download/NLopt-v2.8.0+0/NLopt.v2.8.0.armv7l-linux-musleabihf-cxx03.tar.gz"
[[NLopt]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "46741fde5a2d08c3017a4bbf03469573e4402a9d"
libc = "musl"
os = "linux"

    [[NLopt.download]]
    sha256 = "77e5a469bcc32614014e21ef677c839f438526a2bf686018b1f9025dedd351a2"
    url = "https://github.com/JuliaBinaryWrappers/NLopt_jll.jl/releases/download/NLopt-v2.8.0+0/NLopt.v2.8.0.armv7l-linux-musleabihf-cxx11.tar.gz"
[[NLopt]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "c22470bf0345b5812d1b88b53b0c31355eedb457"
libc = "glibc"
os = "linux"

    [[NLopt.download]]
    sha256 = "4afe50e1e543a480d6312dad3ff39032b6c5be437fd63d55795d5a92c95a8c94"
    url = "https://github.com/JuliaBinaryWrappers/NLopt_jll.jl/releases/download/NLopt-v2.8.0+0/NLopt.v2.8.0.i686-linux-gnu-cxx03.tar.gz"
[[NLopt]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "99d9a73a0de2b1180857698e07605b311e27cb7c"
libc = "glibc"
os = "linux"

    [[NLopt.download]]
    sha256 = "e7fba33b9bce572ae936acde61edc16867ce49a58a5533f2cbf3fc7500de1460"
    url = "https://github.com/JuliaBinaryWrappers/NLopt_jll.jl/releases/download/NLopt-v2.8.0+0/NLopt.v2.8.0.i686-linux-gnu-cxx11.tar.gz"
[[NLopt]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "c6605f193c2e324b304cc94a857f5f92aaf98e20"
libc = "musl"
os = "linux"

    [[NLopt.download]]
    sha256 = "ee39054d181051828cd7c0f867ce530da9d4ea080c03488f3eda3eb97bd2f94e"
    url = "https://github.com/JuliaBinaryWrappers/NLopt_jll.jl/releases/download/NLopt-v2.8.0+0/NLopt.v2.8.0.i686-linux-musl-cxx03.tar.gz"
[[NLopt]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "4ae7f01f43fa7c6b768b79a23aa217757c0b48e7"
libc = "musl"
os = "linux"

    [[NLopt.download]]
    sha256 = "c9d0783c464ae9863234390bc3c354f1dc364c2e31b36ee63556643f29ade8cd"
    url = "https://github.com/JuliaBinaryWrappers/NLopt_jll.jl/releases/download/NLopt-v2.8.0+0/NLopt.v2.8.0.i686-linux-musl-cxx11.tar.gz"
[[NLopt]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "6f46fb210257fba5935d0a4af8adc583bcbb842b"
os = "windows"

    [[NLopt.download]]
    sha256 = "08c08d91effb0fa0848dbff118302d687e9f2c8e33660074323d1454ae587b7b"
    url = "https://github.com/JuliaBinaryWrappers/NLopt_jll.jl/releases/download/NLopt-v2.8.0+0/NLopt.v2.8.0.i686-w64-mingw32-cxx03.tar.gz"
[[NLopt]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c6910d274ab370e67ca49352d286163f771564d5"
os = "windows"

    [[NLopt.download]]
    sha256 = "eeab2ad57d28cfc7f2690ef04b05176362fe921ced2cfc93bf3d42466f0170da"
    url = "https://github.com/JuliaBinaryWrappers/NLopt_jll.jl/releases/download/NLopt-v2.8.0+0/NLopt.v2.8.0.i686-w64-mingw32-cxx11.tar.gz"
[[NLopt]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "bd64de0919372c8eb4900bebb29a76ed19058b92"
libc = "glibc"
os = "linux"

    [[NLopt.download]]
    sha256 = "34ca5c80e7eb1f6b4f9530db6dd4d106778c157490715295f8a4baeb8b59dbdf"
    url = "https://github.com/JuliaBinaryWrappers/NLopt_jll.jl/releases/download/NLopt-v2.8.0+0/NLopt.v2.8.0.powerpc64le-linux-gnu-cxx03.tar.gz"
[[NLopt]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "5dd6fc54e8713476589399d07db38b76dfb2ab0c"
libc = "glibc"
os = "linux"

    [[NLopt.download]]
    sha256 = "6eb9e4ffc24d6f7c5548f76309cc6b0f9bcaf874f1dfe8d236e6fc1f2e8e7e9b"
    url = "https://github.com/JuliaBinaryWrappers/NLopt_jll.jl/releases/download/NLopt-v2.8.0+0/NLopt.v2.8.0.powerpc64le-linux-gnu-cxx11.tar.gz"
[[NLopt]]
arch = "x86_64"
git-tree-sha1 = "c0b8af3ecd3a21ade51d7bfdeb24facc8bb16468"
os = "macos"

    [[NLopt.download]]
    sha256 = "41582c017b4ad68efef931e8cc04758bb654fb9e87f6991ad936322e7bb3e6d7"
    url = "https://github.com/JuliaBinaryWrappers/NLopt_jll.jl/releases/download/NLopt-v2.8.0+0/NLopt.v2.8.0.x86_64-apple-darwin.tar.gz"
[[NLopt]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "cc3d66a44573d5b744cc05f96d23bd5cff550d37"
libc = "glibc"
os = "linux"

    [[NLopt.download]]
    sha256 = "6e5116ff8e21e0a98ae856188bce1333fb44a8e036eebad4c2410bece0fb3e1a"
    url = "https://github.com/JuliaBinaryWrappers/NLopt_jll.jl/releases/download/NLopt-v2.8.0+0/NLopt.v2.8.0.x86_64-linux-gnu-cxx03.tar.gz"
[[NLopt]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "fb8d21cdf72875523ec9ec77a77f087e9414858f"
libc = "glibc"
os = "linux"

    [[NLopt.download]]
    sha256 = "62bd1ceb551cd8113a9aa4d5cc549120c4a1107eda51bd88c5c3608818f5d241"
    url = "https://github.com/JuliaBinaryWrappers/NLopt_jll.jl/releases/download/NLopt-v2.8.0+0/NLopt.v2.8.0.x86_64-linux-gnu-cxx11.tar.gz"
[[NLopt]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "1914376bd6bb3407357b113b65a5c0b3815a7f60"
libc = "musl"
os = "linux"

    [[NLopt.download]]
    sha256 = "4adf3b20400277a4fb8036c9f42919890f23060503fe40bb709c0689bd34858f"
    url = "https://github.com/JuliaBinaryWrappers/NLopt_jll.jl/releases/download/NLopt-v2.8.0+0/NLopt.v2.8.0.x86_64-linux-musl-cxx03.tar.gz"
[[NLopt]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "1d8f6875fd5d23b084c951f87758f297dbf51ed6"
libc = "musl"
os = "linux"

    [[NLopt.download]]
    sha256 = "33a549c727a067603b65ce1f290bdead705e57e299173f33bdbfd433b22b4531"
    url = "https://github.com/JuliaBinaryWrappers/NLopt_jll.jl/releases/download/NLopt-v2.8.0+0/NLopt.v2.8.0.x86_64-linux-musl-cxx11.tar.gz"
[[NLopt]]
arch = "x86_64"
git-tree-sha1 = "7ebedd5b95c1e8687f23002d511e0a535b1daebc"
os = "freebsd"

    [[NLopt.download]]
    sha256 = "cda1253a22aff147a7a310732df51c2866f1806fa11dd13f6ddf372bd80d2340"
    url = "https://github.com/JuliaBinaryWrappers/NLopt_jll.jl/releases/download/NLopt-v2.8.0+0/NLopt.v2.8.0.x86_64-unknown-freebsd.tar.gz"
[[NLopt]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "78ecf1c954638146957126097898b543c485d091"
os = "windows"

    [[NLopt.download]]
    sha256 = "dbecae988950e9edab7be94dcdcc4072973c98241636abc225e30b3ddb721fc1"
    url = "https://github.com/JuliaBinaryWrappers/NLopt_jll.jl/releases/download/NLopt-v2.8.0+0/NLopt.v2.8.0.x86_64-w64-mingw32-cxx03.tar.gz"
[[NLopt]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "0ceeaf8218ceee8aeb7015f00fd6d537fc1b4df8"
os = "windows"

    [[NLopt.download]]
    sha256 = "d37ea22fa221fafa8feb8c299eb65123e5ce24d4822c1e32bf42ebbceb099565"
    url = "https://github.com/JuliaBinaryWrappers/NLopt_jll.jl/releases/download/NLopt-v2.8.0+0/NLopt.v2.8.0.x86_64-w64-mingw32-cxx11.tar.gz"
