[[NLopt]]
arch = "aarch64"
git-tree-sha1 = "45377f07789946f642323e816910a076ccee9269"
os = "macos"

    [[NLopt.download]]
    sha256 = "7d47faf91748c78b379a3aa2f9a1f7f3af8be6f5d0167565317d224d09da14d6"
    url = "https://github.com/JuliaBinaryWrappers/NLopt_jll.jl/releases/download/NLopt-v2.9.0+0/NLopt.v2.9.0.aarch64-apple-darwin.tar.gz"
[[NLopt]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "c050a4ffc96647f1b858823ed3aceaac1881555b"
libc = "glibc"
os = "linux"

    [[NLopt.download]]
    sha256 = "1d2c5caab61d6d14186a6c45e7d4f367afcc31f8560b59b371d2b0f1957766d1"
    url = "https://github.com/JuliaBinaryWrappers/NLopt_jll.jl/releases/download/NLopt-v2.9.0+0/NLopt.v2.9.0.aarch64-linux-gnu-cxx03.tar.gz"
[[NLopt]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "283fd8181da988935afd6a28f0ee4478954ea497"
libc = "glibc"
os = "linux"

    [[NLopt.download]]
    sha256 = "cbe541c3f17af911364641d9a56f22dc479d5326fbbedf0bfc3d7d94b0ebd5f8"
    url = "https://github.com/JuliaBinaryWrappers/NLopt_jll.jl/releases/download/NLopt-v2.9.0+0/NLopt.v2.9.0.aarch64-linux-gnu-cxx11.tar.gz"
[[NLopt]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "ed9d692351be00446a7a237f7bee259c55d69e07"
libc = "musl"
os = "linux"

    [[NLopt.download]]
    sha256 = "9c17688e994dd8d259cfdf4a7c68d2bea32231a86295df888e4d65035261f47b"
    url = "https://github.com/JuliaBinaryWrappers/NLopt_jll.jl/releases/download/NLopt-v2.9.0+0/NLopt.v2.9.0.aarch64-linux-musl-cxx03.tar.gz"
[[NLopt]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b219510eae606421cff11de0cd86a6e6c8810a32"
libc = "musl"
os = "linux"

    [[NLopt.download]]
    sha256 = "8aaeee30e03ffd2a30aed117dd4be303333a71904614f58f74f27a69b456e4e6"
    url = "https://github.com/JuliaBinaryWrappers/NLopt_jll.jl/releases/download/NLopt-v2.9.0+0/NLopt.v2.9.0.aarch64-linux-musl-cxx11.tar.gz"
[[NLopt]]
arch = "aarch64"
git-tree-sha1 = "770b1b109b85971b3ac7922bbbca47c7aebe45a8"
os = "freebsd"

    [[NLopt.download]]
    sha256 = "a37e21daeec43041f7c8d6dfa3c276b7d00957fa86616eb0e683a05ead69e94b"
    url = "https://github.com/JuliaBinaryWrappers/NLopt_jll.jl/releases/download/NLopt-v2.9.0+0/NLopt.v2.9.0.aarch64-unknown-freebsd.tar.gz"
[[NLopt]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "03a09b6505833418787a167f29377917a4fc3100"
libc = "glibc"
os = "linux"

    [[NLopt.download]]
    sha256 = "dca234309ed82a27d78e5e1474463c06e02d0223a0ddb4d1b5e23dc54d95c063"
    url = "https://github.com/JuliaBinaryWrappers/NLopt_jll.jl/releases/download/NLopt-v2.9.0+0/NLopt.v2.9.0.armv6l-linux-gnueabihf-cxx03.tar.gz"
[[NLopt]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "bd16eaa0ac2c4b03542e9ab9d2a3c300c32dc41f"
libc = "glibc"
os = "linux"

    [[NLopt.download]]
    sha256 = "efb577bd4b00414a730e5fe5ceca45a9e5a35ba7d57ee7e41917cafb8f615b62"
    url = "https://github.com/JuliaBinaryWrappers/NLopt_jll.jl/releases/download/NLopt-v2.9.0+0/NLopt.v2.9.0.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[NLopt]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "27175dbe6e0ae7dadd09dc2f3dd7f2c370729384"
libc = "musl"
os = "linux"

    [[NLopt.download]]
    sha256 = "2fbdf7ca516c40ee1f9166c94460638fbcaa96d56d7df2c8f870116d3dd558a5"
    url = "https://github.com/JuliaBinaryWrappers/NLopt_jll.jl/releases/download/NLopt-v2.9.0+0/NLopt.v2.9.0.armv6l-linux-musleabihf-cxx03.tar.gz"
[[NLopt]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c6ffb6330f07caf2c6f0b7b407faf5f895e34c05"
libc = "musl"
os = "linux"

    [[NLopt.download]]
    sha256 = "f1ce08a504e2002512462feaf0f5b96de4c2aaff1c2e16da494e841cb986dd13"
    url = "https://github.com/JuliaBinaryWrappers/NLopt_jll.jl/releases/download/NLopt-v2.9.0+0/NLopt.v2.9.0.armv6l-linux-musleabihf-cxx11.tar.gz"
[[NLopt]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "c23b52f79752dcea594a1eeba720cde313ff3ee4"
libc = "glibc"
os = "linux"

    [[NLopt.download]]
    sha256 = "56a566c0903643493a287f51abed77a7d24fa7267576d145af36dda6013ac481"
    url = "https://github.com/JuliaBinaryWrappers/NLopt_jll.jl/releases/download/NLopt-v2.9.0+0/NLopt.v2.9.0.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[NLopt]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "6d454b947cad5a1fc9591017926f6b1c3c38e6d1"
libc = "glibc"
os = "linux"

    [[NLopt.download]]
    sha256 = "63eab4bcd4870d23e14e96fee0264bb7245f66c1e962cbd9062b4939cd158fb3"
    url = "https://github.com/JuliaBinaryWrappers/NLopt_jll.jl/releases/download/NLopt-v2.9.0+0/NLopt.v2.9.0.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[NLopt]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "ede5a0fa9b09f2c22b3a32f95966d4dee2d0c2fa"
libc = "musl"
os = "linux"

    [[NLopt.download]]
    sha256 = "886175194d126f03baecb741eb53c54d697011025be80a134456719852d8a84d"
    url = "https://github.com/JuliaBinaryWrappers/NLopt_jll.jl/releases/download/NLopt-v2.9.0+0/NLopt.v2.9.0.armv7l-linux-musleabihf-cxx03.tar.gz"
[[NLopt]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "12b5bd22c1a93edb0715296545ca0de8fdc064d3"
libc = "musl"
os = "linux"

    [[NLopt.download]]
    sha256 = "fe07b134ea0be3d727159bddb9ba8b2e1a8c33fec1da2a0a704cc8645a184df4"
    url = "https://github.com/JuliaBinaryWrappers/NLopt_jll.jl/releases/download/NLopt-v2.9.0+0/NLopt.v2.9.0.armv7l-linux-musleabihf-cxx11.tar.gz"
[[NLopt]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "707369dd4226bc216592a6e21f3a41652ae2d873"
libc = "glibc"
os = "linux"

    [[NLopt.download]]
    sha256 = "a8235dfc2537edbc00181b77eb64a48b9e928a0dfd9228bd48970771465face7"
    url = "https://github.com/JuliaBinaryWrappers/NLopt_jll.jl/releases/download/NLopt-v2.9.0+0/NLopt.v2.9.0.i686-linux-gnu-cxx03.tar.gz"
[[NLopt]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "9dc04a31391c5ee7b4a291e4b4b4b94e49345157"
libc = "glibc"
os = "linux"

    [[NLopt.download]]
    sha256 = "2822f736553b0cc0d056eb3a464fb638c592be278acfa9953c77b3346241678a"
    url = "https://github.com/JuliaBinaryWrappers/NLopt_jll.jl/releases/download/NLopt-v2.9.0+0/NLopt.v2.9.0.i686-linux-gnu-cxx11.tar.gz"
[[NLopt]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "0e6386d772d04a0ee3b715c60202bd6a2f1a49ea"
libc = "musl"
os = "linux"

    [[NLopt.download]]
    sha256 = "090ccabe8fa75000f296a48532e8639927b6f4527dfe83efbd1583f59c077367"
    url = "https://github.com/JuliaBinaryWrappers/NLopt_jll.jl/releases/download/NLopt-v2.9.0+0/NLopt.v2.9.0.i686-linux-musl-cxx03.tar.gz"
[[NLopt]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "55d303ed39bf1f438fac2b63c3760cd8f2515edd"
libc = "musl"
os = "linux"

    [[NLopt.download]]
    sha256 = "aaf9cf35120521db23d20d04b9031043abac2793caa4c76e3c30feecb7d2cbfb"
    url = "https://github.com/JuliaBinaryWrappers/NLopt_jll.jl/releases/download/NLopt-v2.9.0+0/NLopt.v2.9.0.i686-linux-musl-cxx11.tar.gz"
[[NLopt]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "1ae3960db49649776506a476a75f97d59b71561e"
os = "windows"

    [[NLopt.download]]
    sha256 = "688ac8b2a6e01f2159fdd763a328c4a9a472a716e2f5c81069b7a223372be7a8"
    url = "https://github.com/JuliaBinaryWrappers/NLopt_jll.jl/releases/download/NLopt-v2.9.0+0/NLopt.v2.9.0.i686-w64-mingw32-cxx03.tar.gz"
[[NLopt]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "0901ae3ab53e30ea2d744fc3d30722b61e9dc625"
os = "windows"

    [[NLopt.download]]
    sha256 = "90cb3541d4478bc5f8479fd09908f1495c8724df22914fc72165898260a9b717"
    url = "https://github.com/JuliaBinaryWrappers/NLopt_jll.jl/releases/download/NLopt-v2.9.0+0/NLopt.v2.9.0.i686-w64-mingw32-cxx11.tar.gz"
[[NLopt]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "de48e5708d2ba684b846d076c57eeab2bd195268"
libc = "glibc"
os = "linux"

    [[NLopt.download]]
    sha256 = "1917c813fdca0102bf11faf6224daf8dea513ea3406d8fba55abe22db97a5b29"
    url = "https://github.com/JuliaBinaryWrappers/NLopt_jll.jl/releases/download/NLopt-v2.9.0+0/NLopt.v2.9.0.powerpc64le-linux-gnu-cxx03.tar.gz"
[[NLopt]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "931c56cbef9bca5c564ff424c21b720b35d13711"
libc = "glibc"
os = "linux"

    [[NLopt.download]]
    sha256 = "8527630db6663d1cfecdeff4c2b88b1cd433a725b150fd6dbfd4482e44775d5e"
    url = "https://github.com/JuliaBinaryWrappers/NLopt_jll.jl/releases/download/NLopt-v2.9.0+0/NLopt.v2.9.0.powerpc64le-linux-gnu-cxx11.tar.gz"
[[NLopt]]
arch = "riscv64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "68c039101d0c33b280128435d421799439a6187d"
libc = "glibc"
os = "linux"

    [[NLopt.download]]
    sha256 = "de15f4d20e6f9d3361fc0c87b025b1fe3b175ccd1ca68e940fe2e72fc9eda1e5"
    url = "https://github.com/JuliaBinaryWrappers/NLopt_jll.jl/releases/download/NLopt-v2.9.0+0/NLopt.v2.9.0.riscv64-linux-gnu-cxx03.tar.gz"
[[NLopt]]
arch = "riscv64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "cedefc1f902eef392d2cb39339f0eb93ac030b58"
libc = "glibc"
os = "linux"

    [[NLopt.download]]
    sha256 = "2fe027c70dff461cd31aaf43a47c5f91735cac67dfe2c32d9706dc64838fd574"
    url = "https://github.com/JuliaBinaryWrappers/NLopt_jll.jl/releases/download/NLopt-v2.9.0+0/NLopt.v2.9.0.riscv64-linux-gnu-cxx11.tar.gz"
[[NLopt]]
arch = "x86_64"
git-tree-sha1 = "de9c4a44de83cc5cd211c11018ddf7319f91b38d"
os = "macos"

    [[NLopt.download]]
    sha256 = "91029c9a613cf87f5998ee4ccdaea785b915270e0cefbd371e7b80cd213b7724"
    url = "https://github.com/JuliaBinaryWrappers/NLopt_jll.jl/releases/download/NLopt-v2.9.0+0/NLopt.v2.9.0.x86_64-apple-darwin.tar.gz"
[[NLopt]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "721273b392c5559fdfbccac5ccf2ad36abdebfee"
libc = "glibc"
os = "linux"

    [[NLopt.download]]
    sha256 = "fc158b336cd071c23a2a062c6a1319f318af9fbe504309f5be022e9e7a26128a"
    url = "https://github.com/JuliaBinaryWrappers/NLopt_jll.jl/releases/download/NLopt-v2.9.0+0/NLopt.v2.9.0.x86_64-linux-gnu-cxx03.tar.gz"
[[NLopt]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "2026ff3d5db026e46eee87d49f4f30a115c083a4"
libc = "glibc"
os = "linux"

    [[NLopt.download]]
    sha256 = "485ad0c2c0b30687a732079a31e5edc9298a46233d1e57b7b578a2f795caa9f6"
    url = "https://github.com/JuliaBinaryWrappers/NLopt_jll.jl/releases/download/NLopt-v2.9.0+0/NLopt.v2.9.0.x86_64-linux-gnu-cxx11.tar.gz"
[[NLopt]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "958e51c7454de25b6220bb2da962a0183725302b"
libc = "musl"
os = "linux"

    [[NLopt.download]]
    sha256 = "8872b08d5d7e35b8ff0b510b7d0e5710a21ff3faba175e117ba7b10695dcf7f1"
    url = "https://github.com/JuliaBinaryWrappers/NLopt_jll.jl/releases/download/NLopt-v2.9.0+0/NLopt.v2.9.0.x86_64-linux-musl-cxx03.tar.gz"
[[NLopt]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "2b4f8e527d1816d85ef0eec98533d3c57d6d398d"
libc = "musl"
os = "linux"

    [[NLopt.download]]
    sha256 = "5a5f716ede9724f48d668d6c85dc75c14015b20e8c23a3583fbd7eefc24e2724"
    url = "https://github.com/JuliaBinaryWrappers/NLopt_jll.jl/releases/download/NLopt-v2.9.0+0/NLopt.v2.9.0.x86_64-linux-musl-cxx11.tar.gz"
[[NLopt]]
arch = "x86_64"
git-tree-sha1 = "8303de38441c0c985807c2ce6b2a9ea276143e8f"
os = "freebsd"

    [[NLopt.download]]
    sha256 = "33ff0fac950ab527251dc97d033f4550e530e1962dd5f4345efc8907a412aaa6"
    url = "https://github.com/JuliaBinaryWrappers/NLopt_jll.jl/releases/download/NLopt-v2.9.0+0/NLopt.v2.9.0.x86_64-unknown-freebsd.tar.gz"
[[NLopt]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "2b1b6ee73e8a2d7b81e45df5f7e7b353f106550c"
os = "windows"

    [[NLopt.download]]
    sha256 = "365d807a0f6e4b8ee0eb9d115ec48a7eadf6d560e92bf110c2079f69a0424409"
    url = "https://github.com/JuliaBinaryWrappers/NLopt_jll.jl/releases/download/NLopt-v2.9.0+0/NLopt.v2.9.0.x86_64-w64-mingw32-cxx03.tar.gz"
[[NLopt]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "39e97505dd165ce086396fbb648ae482102a97a8"
os = "windows"

    [[NLopt.download]]
    sha256 = "b90f3896a7060168bdaeb48d14ed51a00f7e196e277c5db87617dea5206f6dff"
    url = "https://github.com/JuliaBinaryWrappers/NLopt_jll.jl/releases/download/NLopt-v2.9.0+0/NLopt.v2.9.0.x86_64-w64-mingw32-cxx11.tar.gz"
