[[NLopt]]
arch = "aarch64"
git-tree-sha1 = "f85ce0b2b1fb43fd1442f1de541aa77f812ea850"
os = "macos"

    [[NLopt.download]]
    sha256 = "b2f91f3abe988c13064d7dbe556a2f7123afaaa4789e29f39ef9fe74c3f362c6"
    url = "https://github.com/JuliaBinaryWrappers/NLopt_jll.jl/releases/download/NLopt-v2.10.0+0/NLopt.v2.10.0.aarch64-apple-darwin.tar.gz"
[[NLopt]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "f6e813d05b413bf0fcda245b676831657e8b057c"
libc = "glibc"
os = "linux"

    [[NLopt.download]]
    sha256 = "3bc4ae1fa8d75441295318c5bdb8f3b4af337a3c53ecef6a09d608bc2dc168d8"
    url = "https://github.com/JuliaBinaryWrappers/NLopt_jll.jl/releases/download/NLopt-v2.10.0+0/NLopt.v2.10.0.aarch64-linux-gnu-cxx03.tar.gz"
[[NLopt]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "007b812d9a6f700f0959eb422f678bf03d8f623c"
libc = "glibc"
os = "linux"

    [[NLopt.download]]
    sha256 = "a079b110ef09cffa8e82c5b7caacb6da3f98c3573434da3d7b4753007a9986e2"
    url = "https://github.com/JuliaBinaryWrappers/NLopt_jll.jl/releases/download/NLopt-v2.10.0+0/NLopt.v2.10.0.aarch64-linux-gnu-cxx11.tar.gz"
[[NLopt]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "01e1ba3ba84921fbc830a1c48433a3627d944687"
libc = "musl"
os = "linux"

    [[NLopt.download]]
    sha256 = "adebc1620ef036a5ea7f35e651a70f1b01a8fecdd1f6beac936914e53d3f4b8d"
    url = "https://github.com/JuliaBinaryWrappers/NLopt_jll.jl/releases/download/NLopt-v2.10.0+0/NLopt.v2.10.0.aarch64-linux-musl-cxx03.tar.gz"
[[NLopt]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "519466e48a6facfeba017c7cc311b0b7ca69d62d"
libc = "musl"
os = "linux"

    [[NLopt.download]]
    sha256 = "6dbfe1fbe39948e7dcadc205588d7e6ab64890b12017fd15c6bca567f8ee2aa0"
    url = "https://github.com/JuliaBinaryWrappers/NLopt_jll.jl/releases/download/NLopt-v2.10.0+0/NLopt.v2.10.0.aarch64-linux-musl-cxx11.tar.gz"
[[NLopt]]
arch = "aarch64"
git-tree-sha1 = "ae3012dec8b7a505e4ab68a772095d56fe34f11d"
os = "freebsd"

    [[NLopt.download]]
    sha256 = "8f40182aceb89b762fa25c3e5bcfdaf050af05e206547c07fc1d28439d510aa5"
    url = "https://github.com/JuliaBinaryWrappers/NLopt_jll.jl/releases/download/NLopt-v2.10.0+0/NLopt.v2.10.0.aarch64-unknown-freebsd.tar.gz"
[[NLopt]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "9d45461bb16d10fc3affcfb2adc565330ddb5247"
libc = "glibc"
os = "linux"

    [[NLopt.download]]
    sha256 = "16545f9513d13538685a61fb5239a47f1d2f586ed483a0bd9bbee0840703a93f"
    url = "https://github.com/JuliaBinaryWrappers/NLopt_jll.jl/releases/download/NLopt-v2.10.0+0/NLopt.v2.10.0.armv6l-linux-gnueabihf-cxx03.tar.gz"
[[NLopt]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "55b2ddfe1160be83999df97467194374db73ffe1"
libc = "glibc"
os = "linux"

    [[NLopt.download]]
    sha256 = "c74f6ecfb177a825fae6183f09be194d45ad04f57b2c0ca495971b7e0211f8d2"
    url = "https://github.com/JuliaBinaryWrappers/NLopt_jll.jl/releases/download/NLopt-v2.10.0+0/NLopt.v2.10.0.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[NLopt]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "d6b6e4d0cb4deb3ca378b26bb23735683df8ab58"
libc = "musl"
os = "linux"

    [[NLopt.download]]
    sha256 = "b73d6b43aaee72c4bb174afbccb9705db8e0a14c6be334ca12a3d92d5cad6c25"
    url = "https://github.com/JuliaBinaryWrappers/NLopt_jll.jl/releases/download/NLopt-v2.10.0+0/NLopt.v2.10.0.armv6l-linux-musleabihf-cxx03.tar.gz"
[[NLopt]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a2aea3abedde675a2f9025eb521aee7ea55ba72f"
libc = "musl"
os = "linux"

    [[NLopt.download]]
    sha256 = "be375b2a01c3006f7857e3d4f8da1d6c7d37f026d24e889b6dd4a8113f6ad4e3"
    url = "https://github.com/JuliaBinaryWrappers/NLopt_jll.jl/releases/download/NLopt-v2.10.0+0/NLopt.v2.10.0.armv6l-linux-musleabihf-cxx11.tar.gz"
[[NLopt]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "465e466b349ef4808a362b35a6652d456f19b5e3"
libc = "glibc"
os = "linux"

    [[NLopt.download]]
    sha256 = "e674cc593494756be662735508c41f42c551f23774b148e1e05d3f1916aaaa9b"
    url = "https://github.com/JuliaBinaryWrappers/NLopt_jll.jl/releases/download/NLopt-v2.10.0+0/NLopt.v2.10.0.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[NLopt]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "55d0becce635e70d7dec355280861a1e936dbd57"
libc = "glibc"
os = "linux"

    [[NLopt.download]]
    sha256 = "759166072411bac45ccff4939ebccd209d49fe9e06e61c6d2f16438ae7fed6c0"
    url = "https://github.com/JuliaBinaryWrappers/NLopt_jll.jl/releases/download/NLopt-v2.10.0+0/NLopt.v2.10.0.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[NLopt]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "f699ef93dc79069f14eb29d2ed5d28125fa4e581"
libc = "musl"
os = "linux"

    [[NLopt.download]]
    sha256 = "ce476dd12bc32dd8c77b86b8c62290ee29fcaa7b41f4cb8115bd08bb467672cc"
    url = "https://github.com/JuliaBinaryWrappers/NLopt_jll.jl/releases/download/NLopt-v2.10.0+0/NLopt.v2.10.0.armv7l-linux-musleabihf-cxx03.tar.gz"
[[NLopt]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b56cffb1b52a5d30a43d32d079113dad79b53a99"
libc = "musl"
os = "linux"

    [[NLopt.download]]
    sha256 = "996802e34aa7fe282275c8ba6cc7ab8729dbafeb7cf9833ae074d95708ea0c54"
    url = "https://github.com/JuliaBinaryWrappers/NLopt_jll.jl/releases/download/NLopt-v2.10.0+0/NLopt.v2.10.0.armv7l-linux-musleabihf-cxx11.tar.gz"
[[NLopt]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "a2a291357d17eee2699e2de7481f83d79a22c3a8"
libc = "glibc"
os = "linux"

    [[NLopt.download]]
    sha256 = "7d26dc6560ab5c6af02bffb5dfa4a4bc23f9c0af2ecf21d8db380eea1dc62b09"
    url = "https://github.com/JuliaBinaryWrappers/NLopt_jll.jl/releases/download/NLopt-v2.10.0+0/NLopt.v2.10.0.i686-linux-gnu-cxx03.tar.gz"
[[NLopt]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "8bdaa2545379f69805130ef823a63ee573cc1cdf"
libc = "glibc"
os = "linux"

    [[NLopt.download]]
    sha256 = "6d4be6d9d83d638c57af534ab8b4ea80602b3b1b05a2612289995083af54e2b4"
    url = "https://github.com/JuliaBinaryWrappers/NLopt_jll.jl/releases/download/NLopt-v2.10.0+0/NLopt.v2.10.0.i686-linux-gnu-cxx11.tar.gz"
[[NLopt]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "bb35708217a73f58742c65aee55ff8cadfcc7a20"
libc = "musl"
os = "linux"

    [[NLopt.download]]
    sha256 = "b8db8e6210ea0ab6eb9c2d7c1c933c329043471102a7fc86cdbafd403039f17a"
    url = "https://github.com/JuliaBinaryWrappers/NLopt_jll.jl/releases/download/NLopt-v2.10.0+0/NLopt.v2.10.0.i686-linux-musl-cxx03.tar.gz"
[[NLopt]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "442ef01da12f7ec6c0ef42e7f4d634070fc791b1"
libc = "musl"
os = "linux"

    [[NLopt.download]]
    sha256 = "588386cc5757ec9e9bdef9bacbd53c5283008eec2191fc41652aae3c34821a8c"
    url = "https://github.com/JuliaBinaryWrappers/NLopt_jll.jl/releases/download/NLopt-v2.10.0+0/NLopt.v2.10.0.i686-linux-musl-cxx11.tar.gz"
[[NLopt]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "d46896b09e095e2a2603e3cc74804bb2e70b651f"
os = "windows"

    [[NLopt.download]]
    sha256 = "e3514ca61c91c2b0054a931b1925183374afb927950ed5c9ada3b9ed91b1b98a"
    url = "https://github.com/JuliaBinaryWrappers/NLopt_jll.jl/releases/download/NLopt-v2.10.0+0/NLopt.v2.10.0.i686-w64-mingw32-cxx03.tar.gz"
[[NLopt]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "22acb39d783b9ece5d732c8318f623734dd4c46d"
os = "windows"

    [[NLopt.download]]
    sha256 = "cb4c199184abbed90132420f24b8b8dd0864a43bd438ac0da244d3f0a77f6bff"
    url = "https://github.com/JuliaBinaryWrappers/NLopt_jll.jl/releases/download/NLopt-v2.10.0+0/NLopt.v2.10.0.i686-w64-mingw32-cxx11.tar.gz"
[[NLopt]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "86c10fb7fe473d1b5c8568b45248c5ec96887635"
libc = "glibc"
os = "linux"

    [[NLopt.download]]
    sha256 = "c3480b5601fb7d0776d67d0afb2c6b4016791c704e121a9f7f52dec25f591886"
    url = "https://github.com/JuliaBinaryWrappers/NLopt_jll.jl/releases/download/NLopt-v2.10.0+0/NLopt.v2.10.0.powerpc64le-linux-gnu-cxx03.tar.gz"
[[NLopt]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "dfb13e21d35cb45cd4d9209d93f065895183a342"
libc = "glibc"
os = "linux"

    [[NLopt.download]]
    sha256 = "ce0acb7c386a250680248ed8acfcb63395e0b95109145c96d45e2d7f423cf7f4"
    url = "https://github.com/JuliaBinaryWrappers/NLopt_jll.jl/releases/download/NLopt-v2.10.0+0/NLopt.v2.10.0.powerpc64le-linux-gnu-cxx11.tar.gz"
[[NLopt]]
arch = "riscv64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "46fc23698b5298fc1f4a2a4b9e75c61d22c812dd"
libc = "glibc"
os = "linux"

    [[NLopt.download]]
    sha256 = "c1619da46ec332a96a4b095e700a7eaf756eacd6dd0e20f941f7aa4e27267613"
    url = "https://github.com/JuliaBinaryWrappers/NLopt_jll.jl/releases/download/NLopt-v2.10.0+0/NLopt.v2.10.0.riscv64-linux-gnu-cxx03.tar.gz"
[[NLopt]]
arch = "riscv64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "9142a9ad7d4c2aa7ef0db6c8baa5e7464870ba69"
libc = "glibc"
os = "linux"

    [[NLopt.download]]
    sha256 = "16e8fb0e2e1a91dd932a46c167c50fddf8f7deb6c80c1853514ff7225acd385b"
    url = "https://github.com/JuliaBinaryWrappers/NLopt_jll.jl/releases/download/NLopt-v2.10.0+0/NLopt.v2.10.0.riscv64-linux-gnu-cxx11.tar.gz"
[[NLopt]]
arch = "x86_64"
git-tree-sha1 = "e2ccaa571b252de7e1d1651d852de9fa358ea568"
os = "macos"

    [[NLopt.download]]
    sha256 = "f59822b5bc8d24c292c426dd02f8c0874778627751b357cf4ca629dd2fb90a72"
    url = "https://github.com/JuliaBinaryWrappers/NLopt_jll.jl/releases/download/NLopt-v2.10.0+0/NLopt.v2.10.0.x86_64-apple-darwin.tar.gz"
[[NLopt]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "3e51043115c4dd5e13ea92d2a2c69cdfd4a791b3"
libc = "glibc"
os = "linux"

    [[NLopt.download]]
    sha256 = "50cebe7836a9241ffd45e758e213f5d90ff267628fc1e7f3e8953bdd106535ba"
    url = "https://github.com/JuliaBinaryWrappers/NLopt_jll.jl/releases/download/NLopt-v2.10.0+0/NLopt.v2.10.0.x86_64-linux-gnu-cxx03.tar.gz"
[[NLopt]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "66be17094f099d5b2ed33cf346c161e8c458a0c2"
libc = "glibc"
os = "linux"

    [[NLopt.download]]
    sha256 = "585ff3e77766f16989acce391a24ffd3137daa4edd99620e0eeafdbdd7bbbb7e"
    url = "https://github.com/JuliaBinaryWrappers/NLopt_jll.jl/releases/download/NLopt-v2.10.0+0/NLopt.v2.10.0.x86_64-linux-gnu-cxx11.tar.gz"
[[NLopt]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "af1e684f9b05a409a207afe0491ecd6c559f2baf"
libc = "musl"
os = "linux"

    [[NLopt.download]]
    sha256 = "cae6bbd872773f987f08a7343cdd46813534077708f31ccf080a5777754e8a79"
    url = "https://github.com/JuliaBinaryWrappers/NLopt_jll.jl/releases/download/NLopt-v2.10.0+0/NLopt.v2.10.0.x86_64-linux-musl-cxx03.tar.gz"
[[NLopt]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "073ddfd8c8b5f7319eceab9fa2ee043a7b52f5e8"
libc = "musl"
os = "linux"

    [[NLopt.download]]
    sha256 = "3818f5862e2e1c72277359535973f12dbca02d3c21b623f3616916a0c7672854"
    url = "https://github.com/JuliaBinaryWrappers/NLopt_jll.jl/releases/download/NLopt-v2.10.0+0/NLopt.v2.10.0.x86_64-linux-musl-cxx11.tar.gz"
[[NLopt]]
arch = "x86_64"
git-tree-sha1 = "05693b00c8b84224c5b153c1ab3bbcfb65987926"
os = "freebsd"

    [[NLopt.download]]
    sha256 = "7c54eedf9bbabcd1afa972e7383d4763573f34e7d0d96fa5432778d66a0898e6"
    url = "https://github.com/JuliaBinaryWrappers/NLopt_jll.jl/releases/download/NLopt-v2.10.0+0/NLopt.v2.10.0.x86_64-unknown-freebsd.tar.gz"
[[NLopt]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "cc2cfdc5b60bad5f1796e327934fefd42422c7ad"
os = "windows"

    [[NLopt.download]]
    sha256 = "a2964da3fe87479af87be0cb0f9f59a0274e5a75af08e62ca15326c59cf7185e"
    url = "https://github.com/JuliaBinaryWrappers/NLopt_jll.jl/releases/download/NLopt-v2.10.0+0/NLopt.v2.10.0.x86_64-w64-mingw32-cxx03.tar.gz"
[[NLopt]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "eeb70635b0737dcf44fdced2d144f66b9a080a6d"
os = "windows"

    [[NLopt.download]]
    sha256 = "b93acf558f97011464372b933bd49b58c449b9e39125ba0e2aa711f3067dfb68"
    url = "https://github.com/JuliaBinaryWrappers/NLopt_jll.jl/releases/download/NLopt-v2.10.0+0/NLopt.v2.10.0.x86_64-w64-mingw32-cxx11.tar.gz"
