[[NLopt]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "8404b891b0a2ee7e4005b7d53da6d4db52dcccb6"
libc = "glibc"
os = "linux"

    [[NLopt.download]]
    sha256 = "62ae1cb259dc172daf4e802d7f8e8575035d33ac589758f27ef36621e75e7419"
    url = "https://github.com/JuliaBinaryWrappers/NLopt_jll.jl/releases/download/NLopt-v2.7.0+0/NLopt.v2.7.0.aarch64-linux-gnu-cxx03.tar.gz"
[[NLopt]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "58967aa8af73259b4f6abc23c0335e65ff552a75"
libc = "glibc"
os = "linux"

    [[NLopt.download]]
    sha256 = "f3c5bf63a67b491d5204bf30b6c7e71a442c902ef04ca0bd6620ba4a71d60b21"
    url = "https://github.com/JuliaBinaryWrappers/NLopt_jll.jl/releases/download/NLopt-v2.7.0+0/NLopt.v2.7.0.aarch64-linux-gnu-cxx11.tar.gz"
[[NLopt]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "ec978e2268240b99b686fb937521db21da725e3b"
libc = "musl"
os = "linux"

    [[NLopt.download]]
    sha256 = "f9127c67cf19ab8e3daa90fffef99b162af366cbda42874e68a8f4101aaa9e30"
    url = "https://github.com/JuliaBinaryWrappers/NLopt_jll.jl/releases/download/NLopt-v2.7.0+0/NLopt.v2.7.0.aarch64-linux-musl-cxx03.tar.gz"
[[NLopt]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "5681e4364437baa8b8262f176d72bcc91381b8a1"
libc = "musl"
os = "linux"

    [[NLopt.download]]
    sha256 = "c2617c9ba9eb02034d06f642934b87a225013f5a01c7a170c08e1ebdd4e8ad1c"
    url = "https://github.com/JuliaBinaryWrappers/NLopt_jll.jl/releases/download/NLopt-v2.7.0+0/NLopt.v2.7.0.aarch64-linux-musl-cxx11.tar.gz"
[[NLopt]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "f6d6b054ed3e8a9593557b86230415513a0e4940"
libc = "glibc"
os = "linux"

    [[NLopt.download]]
    sha256 = "6cdd0dd3a0f93662c1670486c00126b350d443a0c510131d2b9fc2e6088f4262"
    url = "https://github.com/JuliaBinaryWrappers/NLopt_jll.jl/releases/download/NLopt-v2.7.0+0/NLopt.v2.7.0.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[NLopt]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "da9067cec9c5499248f6d803b1f1dd6c743ae5dc"
libc = "glibc"
os = "linux"

    [[NLopt.download]]
    sha256 = "4ef9b13e00114530282057943bb10a027a360f21de9ab0f5f50067611a9401a0"
    url = "https://github.com/JuliaBinaryWrappers/NLopt_jll.jl/releases/download/NLopt-v2.7.0+0/NLopt.v2.7.0.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[NLopt]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "b455de888a65b7bd4c0b36475fa29099c1e6045c"
libc = "musl"
os = "linux"

    [[NLopt.download]]
    sha256 = "679357163a95bd0137b94fb9323c2f3d7d4c30ebd144e0f3cacecd077c9d4eca"
    url = "https://github.com/JuliaBinaryWrappers/NLopt_jll.jl/releases/download/NLopt-v2.7.0+0/NLopt.v2.7.0.armv7l-linux-musleabihf-cxx03.tar.gz"
[[NLopt]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "eb25c3041871c02437671a93fcc1bc82dd7939e5"
libc = "musl"
os = "linux"

    [[NLopt.download]]
    sha256 = "f5b0c306aa6a4b0018e81e1085231102c66a350b29d6d68534792c33abda4f01"
    url = "https://github.com/JuliaBinaryWrappers/NLopt_jll.jl/releases/download/NLopt-v2.7.0+0/NLopt.v2.7.0.armv7l-linux-musleabihf-cxx11.tar.gz"
[[NLopt]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "fd5cb2d8aca291c4d34e384555ae04956b04d9fb"
libc = "glibc"
os = "linux"

    [[NLopt.download]]
    sha256 = "01ad22f23c3605e2f5259e475d0b0e696ec9e1b164c0c3df9fbc016cfa62676a"
    url = "https://github.com/JuliaBinaryWrappers/NLopt_jll.jl/releases/download/NLopt-v2.7.0+0/NLopt.v2.7.0.i686-linux-gnu-cxx03.tar.gz"
[[NLopt]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "4af8409d73509c079911349be539fe55831a8f09"
libc = "glibc"
os = "linux"

    [[NLopt.download]]
    sha256 = "ee18113e867da05f943b65854f67cd2b74ea0291ae9d37559b6308cbe9d9141d"
    url = "https://github.com/JuliaBinaryWrappers/NLopt_jll.jl/releases/download/NLopt-v2.7.0+0/NLopt.v2.7.0.i686-linux-gnu-cxx11.tar.gz"
[[NLopt]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "2f35a76a63b0b4069b5df7c07ca79c61991b2285"
libc = "musl"
os = "linux"

    [[NLopt.download]]
    sha256 = "40bc661a3324bc95db8ffba4d8c044072a3bcedbb5c79e8e96a52f51671d2364"
    url = "https://github.com/JuliaBinaryWrappers/NLopt_jll.jl/releases/download/NLopt-v2.7.0+0/NLopt.v2.7.0.i686-linux-musl-cxx03.tar.gz"
[[NLopt]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "4342885ceac803288706633f07d4443c430d311c"
libc = "musl"
os = "linux"

    [[NLopt.download]]
    sha256 = "67b8ae763e7702d378b6cb928c00048b0237e29fc532682dabf42f7098fb8f3b"
    url = "https://github.com/JuliaBinaryWrappers/NLopt_jll.jl/releases/download/NLopt-v2.7.0+0/NLopt.v2.7.0.i686-linux-musl-cxx11.tar.gz"
[[NLopt]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "c42bb5755bd665cadbb2b5a2430ee5e1d7989983"
os = "windows"

    [[NLopt.download]]
    sha256 = "b13639afa487c7ff07af2ccf0a24fa177bde4e32788a29fc54316d8c7f8ae71b"
    url = "https://github.com/JuliaBinaryWrappers/NLopt_jll.jl/releases/download/NLopt-v2.7.0+0/NLopt.v2.7.0.i686-w64-mingw32-cxx03.tar.gz"
[[NLopt]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "67dbfe52e919b0d20835e183a51f3fc075b9d064"
os = "windows"

    [[NLopt.download]]
    sha256 = "2d77a12a06e7ce250c2871d01bb678d73161f3a065bee61843836e88bc316e74"
    url = "https://github.com/JuliaBinaryWrappers/NLopt_jll.jl/releases/download/NLopt-v2.7.0+0/NLopt.v2.7.0.i686-w64-mingw32-cxx11.tar.gz"
[[NLopt]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "a2a84fae68460a0f45476df517a376ea1b1f734f"
libc = "glibc"
os = "linux"

    [[NLopt.download]]
    sha256 = "854d7211b6a38564bf59a25943fe7df6ec9717a66e5be74e73272ad3e43676dd"
    url = "https://github.com/JuliaBinaryWrappers/NLopt_jll.jl/releases/download/NLopt-v2.7.0+0/NLopt.v2.7.0.powerpc64le-linux-gnu-cxx03.tar.gz"
[[NLopt]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "bd2a26c316be1f0bed4bb8f78462631c90a941a2"
libc = "glibc"
os = "linux"

    [[NLopt.download]]
    sha256 = "3b22b85312d9cb55667e04cbac5ccb3ba9934355ce03811109db1d4d1465bff3"
    url = "https://github.com/JuliaBinaryWrappers/NLopt_jll.jl/releases/download/NLopt-v2.7.0+0/NLopt.v2.7.0.powerpc64le-linux-gnu-cxx11.tar.gz"
[[NLopt]]
arch = "x86_64"
git-tree-sha1 = "bc38fd3e3a8c86297f0d2e0fef8c9397d4f38673"
os = "macos"

    [[NLopt.download]]
    sha256 = "f8a9afd3b7f1d1e0eab88cb6a569a81829d105616d0b65d1efd23f38aad45b3e"
    url = "https://github.com/JuliaBinaryWrappers/NLopt_jll.jl/releases/download/NLopt-v2.7.0+0/NLopt.v2.7.0.x86_64-apple-darwin.tar.gz"
[[NLopt]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "5217d71f380eb5ff3b29dd125bebd523dc182f7c"
libc = "glibc"
os = "linux"

    [[NLopt.download]]
    sha256 = "ef1d4a72abc2ab7a2ce55f84e3bf81a9e640ca543f16658db75f2c4e28309944"
    url = "https://github.com/JuliaBinaryWrappers/NLopt_jll.jl/releases/download/NLopt-v2.7.0+0/NLopt.v2.7.0.x86_64-linux-gnu-cxx03.tar.gz"
[[NLopt]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b6b3a6b7407f80385d7dd00275aa41d78e39abd9"
libc = "glibc"
os = "linux"

    [[NLopt.download]]
    sha256 = "4731f44bfacc2dedc64f267faa93d29646b2c60031df06d3e2314dea939ad180"
    url = "https://github.com/JuliaBinaryWrappers/NLopt_jll.jl/releases/download/NLopt-v2.7.0+0/NLopt.v2.7.0.x86_64-linux-gnu-cxx11.tar.gz"
[[NLopt]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "a5cfaf1c667576a66be2e585961fccebb4016167"
libc = "musl"
os = "linux"

    [[NLopt.download]]
    sha256 = "3e4a57280488d60bd1309edce89186d5312d4eafe42628e4ea5ac193297850e5"
    url = "https://github.com/JuliaBinaryWrappers/NLopt_jll.jl/releases/download/NLopt-v2.7.0+0/NLopt.v2.7.0.x86_64-linux-musl-cxx03.tar.gz"
[[NLopt]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "612602af34b8c19dc3eadb2c44198f4e3ffc0f8a"
libc = "musl"
os = "linux"

    [[NLopt.download]]
    sha256 = "9e8417c4f3b851bf0b3d724fa8f5e746ec373078db27851d949045e037e576ca"
    url = "https://github.com/JuliaBinaryWrappers/NLopt_jll.jl/releases/download/NLopt-v2.7.0+0/NLopt.v2.7.0.x86_64-linux-musl-cxx11.tar.gz"
[[NLopt]]
arch = "x86_64"
git-tree-sha1 = "db2ae73328052b9ad81d93b6c896223e044f2482"
os = "freebsd"

    [[NLopt.download]]
    sha256 = "281090b35d3fa0707edd3c1a388e980da66fb3120471a17bcf757433015b65a7"
    url = "https://github.com/JuliaBinaryWrappers/NLopt_jll.jl/releases/download/NLopt-v2.7.0+0/NLopt.v2.7.0.x86_64-unknown-freebsd.tar.gz"
[[NLopt]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "af9ec79d4299cc70c8ec0ee8d5ee28f6519a5722"
os = "windows"

    [[NLopt.download]]
    sha256 = "f2dad5b592606b96722bf3c50ae746b2299025a2d6f8a40ccaba1992d6bb15ef"
    url = "https://github.com/JuliaBinaryWrappers/NLopt_jll.jl/releases/download/NLopt-v2.7.0+0/NLopt.v2.7.0.x86_64-w64-mingw32-cxx03.tar.gz"
[[NLopt]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "8b33be574b57fff0894a148ed406216761aed31e"
os = "windows"

    [[NLopt.download]]
    sha256 = "37b647f3674ea64454cabb81ab929501ba0e67d0c4e240fce456519dead4898e"
    url = "https://github.com/JuliaBinaryWrappers/NLopt_jll.jl/releases/download/NLopt-v2.7.0+0/NLopt.v2.7.0.x86_64-w64-mingw32-cxx11.tar.gz"
